### ISSUE TITLE
Patching events["end_time"] Alone Returns Error 400 Due to Failing Validator

### ISSUE THREAD

**Issue by marcoep** [amiv-eth/amivapi#134]
How to reproduce:
1. post event with neither time_start nor time_end (so both are Null)
2. patch some time_start
3. try to patch time_end with a correct, later datetime string, amivapi will return 400

The following error is raised:
```
--------------------------------------------------------------------------------
ERROR in patch [/home/marco/playground/amivapi3/src/eve/eve/methods/patch.py:234]:
can't compare offset-naive and offset-aware datetimes
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marco/playground/amivapi3/src/eve/eve/methods/patch.py", line 162, in patch_internal
    original)
  File "/home/marco/playground/amivapi3/src/eve/eve/io/mongo/validation.py", line 79, in validate_update
    return super(Validator, self).validate_update(document)
  File "/home/marco/playground/amivapi3/lib/python3.5/site-packages/cerberus/cerberus.py", line 216, in validate_update
    return self._validate(document, schema, update=True, context=context)
  File "/home/marco/playground/amivapi3/lib/python3.5/site-packages/cerberus/cerberus.py", line 282, in _validate
    self._validate_definition(definition, field, value)
  File "/home/marco/playground/amivapi3/lib/python3.5/site-packages/cerberus/cerberus.py", line 349, in _validate_definition
    validator(definition[rule], field, value)
  File "/home/marco/playground/amivapi/amivapi/events/validation.py", line 197, in _validate_later_than
    if value < first_time:
TypeError: can't compare offset-naive and offset-aware datetimes
127.0.0.1 - - [13/Nov/2016 18:49:33] "PATCH /events/582847f51958641f3842d587 HTTP/1.1" 400 -
```

Pls fix.

**Comment by Tar-Tarus** [comment]
If I have understood the error message correctly, the problem lies in the presence of __time-zone support__ in one of the two elements and the absence thereof in the other element. Correct?

**Comment by NotSpecial** [comment]
I'm on it. I discovered more problems. The validators currently don't really work with patching. E.g. you can also patch the start date to a point in time after the end date (since if you only modify the start date, the validation rule 'later_then' never comes into play since its only checking the end_date field)
