### ISSUE TITLE
Timezone error in media endpoint

### ISSUE THREAD

**Issue by Leonidaz0r** [amiv-eth/amivapi#150]
Some requests to the media endpoint seem to generate errors. From the logfile:

Error on request:
Traceback (most recent call last):
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/werkzeug/serving.py", line 194, in run_wsgi
    execute(self.server.app)Error on request:
Traceback (most recent call last):
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/werkzeug/serving.py", line 194, in run_wsgi
    execute(self.server.app)
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/werkzeug/serving.py", line 182, in execute
    application_iter = app(environ, start_response)
  File "/home/amiv/amivapi/pyenv/src/eve/eve/flaskapp.py", line 1014, in __call__
    return super(Eve, self).__call__(environ, start_response)
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()Error on request:
Traceback (most recent call last):
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/werkzeug/serving.py", line 194, in run_wsgi
    execute(self.server.app)
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/werkzeug/serving.py", line 182, in execute
    application_iter = app(environ, start_response)
  File "/home/amiv/amivapi/pyenv/src/eve/eve/flaskapp.py", line 1014, in __call__
    return super(Eve, self).__call__(environ, start_response)
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/amiv/amivapi/pyenv/src/eve/eve/endpoints.py", line 187, in media_endpoint
    if if_modified_since > file_.upload_date:
TypeError: can't compare offset-naive and offset-aware datetimes

  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/amiv/amivapi/pyenv/src/eve/eve/endpoints.py", line 187, in media_endpoint
    if if_modified_since > file_.upload_date:
TypeError: can't compare offset-naive and offset-aware datetimes

  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/werkzeug/serving.py", line 182, in execute
    application_iter = app(environ, start_response)
  File "/home/amiv/amivapi/pyenv/src/eve/eve/flaskapp.py", line 1014, in __call__
    return super(Eve, self).__call__(environ, start_response)
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/amiv/amivapi/pyenv/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/amiv/amivapi/pyenv/src/eve/eve/endpoints.py", line 187, in media_endpoint
    if if_modified_since > file_.upload_date:
TypeError: can't compare offset-naive and offset-aware datetimes

**Comment by Leonidaz0r** [comment]
The error seems to appear, if one gets a file too often.

**Comment by NotSpecial** [comment]
We get imezone errors again, but this time with file updated times? I wonder why this only occurs if requesting a file a lot.

**Comment by Leonidaz0r** [comment]
I investigated. The error appears if the header "If-Modified-Since" is set. So it is not about request timing, but rather happens when refreshing the page in the browser and the browser has a cached version.

The error appears here: https://github.com/nicolaiarocci/eve/blob/develop/eve/endpoints.py#L182

In line 182 the presence of the If-Modified-Since header is checked. Line 187 then does the comparison, which leads to the exception and subsequent to the error 500.

Eve assumes the updated time of media files has the UTC timezone attached, which we did not attach so far. See my pull request for a fix.

**Comment by NotSpecial** [comment]
Nice find! Timezone problems everywhere ^^

**Comment by Leonidaz0r** [comment]
I have created an issue at eve. This system is a mess. See nicolaiarocci/eve#949

**Comment by NotSpecial** [comment]
Closed by #155
