### ISSUE TITLE
API crashes on GET to /permissions

### ISSUE THREAD

**Issue by Leonidaz0r** [amiv-eth/amivapi#87]
A get to /permissions crashes on the testing server. Crash happens with root user and my own user. Error output from log file:

>Traceback (most recent call last):
>  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
>    return self.wsgi_app(environ, start_response)
>  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
>    response = self.make_response(self.handle_exception(e))
>  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
>    reraise(exc_type, exc_value, tb)
>  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
>    response = self.full_dispatch_request()
>  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
>    rv = self.handle_user_exception(e)
>  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
>    reraise(exc_type, exc_value, tb)
>  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
>    rv = self.dispatch_request()
>  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
>    return self.view_functions[rule.endpoint](**req.view_args)
>  File "/var/www/amivapi/src/src/eve/eve/endpoints.py", line 54, in collections_endpoint
>    response = get(resource, lookup)
>  File "/var/www/amivapi/src/src/eve/eve/methods/common.py", line 241, in rate_limited
>    return f(*args, **kwargs)
>  File "/var/www/amivapi/src/src/eve/eve/auth.py", line 68, in decorated
>    return f(*args, **kwargs)
>  File "/var/www/amivapi/src/src/eve/eve/methods/common.py", line 879, in decorated
>    r = f(resource, **combined_args)
>  File "/var/www/amivapi/src/src/eve/eve/methods/get.py", line 104, in get
>    build_response_document(document, resource, embedded_fields)
>  File "/var/www/amivapi/src/src/eve/eve/methods/common.py", line 434, in >build_response_document
>    document[config.LAST_UPDATED] = last_updated(document)
>  File "/var/www/amivapi/src/src/eve/eve/methods/common.py", line 265, in last_updated
>    return document[config.LAST_UPDATED].replace(tzinfo=None)
>AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by Leonidaz0r** [comment]
The mistake was in an invalid dataset in the database table. Removing the dataset fixed the problem.
